### PR TITLE
Switch to `lrc_kit` for synced lyrics.

### PR DESCRIPTION
**Pull request by reteps**
This library (that I wrote) provides `lrc` downloads from the following sites:

* Sogeci
* LyricFind
* Music163
* RentanaAdvisor
* Megalobiz
* Mooflac
* Syair

### CODE REVIEW

**Review by SimonIT — CHANGES_REQUESTED** [review]
Hey! Thanks you very much for these changes. It will definitely improve this program.

I got some problems with the changes you made. You just replace all lyrics synced lyrics providers with yours, with is totally fine because you got the same and more, but if I want to add some others, it will be more work for me.
The next thing is, that the local lyrics directory doesn't work anymore as intended. I would like to keep the logic that at first in the local lyrics directory is searched and then online.
The last thing that won't work anymore is the caching. It's very nice feature which I would like to kep, too.

I will test the changes the next days

**Comment by reteps** [comment]
ok, willl fix

**Comment by SimonIT** [comment]
Another thing that came to my mind is error catching. Lyrics crawling is a heavy network dependant task. If we don't catch possible connection errors it will harm the user experience.
For example I added in the last release as lyrics source. I didn't catched the errors from and got at least 50 errors on my issue tracker.

**Comment by reteps** [comment]
A little better.

Ideally the lyric retrieval method could be improved a lot, as it is just a massive dirty hack to get the lyrics.

**Comment by reteps** [comment]
The `lrc_kit` is now updated, so it is much faster.

**Comment by SimonIT** [comment]
That's nice to hear. But I can't merge it until my requested changes are fulfilled

**Comment by reteps** [comment]
ok, will fix this weekend

**Comment by reteps** [comment]
@SimonIT I am no longer interested in merging this, I am going to close. https://github.com/khanhas/genius-spicetify

**Comment by reteps** [comment]
Note that the `lrc_kit` is very easy to use and it would be good to separate the lyrics fetching, so it may still be worth looking into.

**Comment by SimonIT** [comment]
Yes, I plan to adapt the providers which aren't there already

**Pull request closed without merging**
